train:
  _target_: src.datasets.LJSpeechDataset
  name: "train"
  audio_path: "/home/georgii/Downloads/LJSpeech-1.1"
  index_audio_path: "/home/georgii/Downloads/LJSpeech-1.1"
  limit: 8
  segment_length: 8191
  mel_config:
    _target_: src.utils.MelSpectrogramConfig
    sr: 22050
    win_length: 1024
    hop_length: 256
    n_fft: 1024
    f_min: 0
    f_max: 8000
    n_mels: 80
    power: 1.0
    pad_value: -11.5129251

val:
  _target_: src.datasets.LJSpeechDataset
  name: "val"
  audio_path: "/home/georgii/Downloads/LJSpeech-1.1"
  index_audio_path: "/home/georgii/Downloads/LJSpeech-1.1"
  limit: 8
  segment_length: 8191
  mel_config:
    _target_: src.utils.MelSpectrogramConfig
    sr: 22050
    win_length: 1024
    hop_length: 256
    n_fft: 1024
    f_min: 0
    f_max: 8000
    n_mels: 80
    power: 1.0
    pad_value: -11.5129251
