device: "auto"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
    group_size: 1
  - _target_: src.metrics.LSD
    device: ${metrics.device}
    name: "LSD"
    n_fft: 1024
    hop_length: 256
    win_length: 1024
