device: "auto"
train: # metrics that are calculated during training
#  - _target_: src.metrics.PESQ
#    device: ${metrics.device}
#    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.PESQ
    device: ${metrics.device}
    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
