device: "auto"
train:
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
    group_size: 3
inference: # metrics that are calculated during inference (eval)
#  - _target_: src.metrics.PESQ
#    device: ${metrics.device}
#    name: "PESQ"
  - _target_: src.metrics.STOI
    device: ${metrics.device}
    name: "STOI"
