_target_: src.model.HiFiGAN_Plus_Mel
generator_params:
  in_channels: 80
  upsample_rates: [8,8,2,2]
  upsample_initial_channel: 512
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1,3,5],[1,3,5],[1,3,5]]
discriminator_params:
  num_scales: 3
  scale_factor: 2
