_target_: src.model.LightVoc
generator_params:
  n_mels: 80
  d_model: 256
  d_ff: 1024
  n_heads: 4
  num_conformer_blocks: 6
  conv_kernel_size: 31
  n_fft: 1024
  hop_length: 256
  win_length: 256
  dropout: 0.1

discriminator_params:
  combd_params:
    h:
      combd_h_u: [[32, 64], [64, 128], [128, 256]]
      combd_d_k: [[5, 3, 3], [5, 3, 3], [5, 3, 3]]
      combd_d_s: [[2, 2, 2], [2, 2, 2], [2, 2, 2]]
      combd_d_d: [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
      combd_d_g: [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
      combd_d_p: [[2, 1, 1], [2, 1, 1], [2, 1, 1]]
      combd_op_f: [1, 1, 1]
      combd_op_k: [3, 3, 3]
      combd_op_g: [1, 1, 1]
      pqmf_config:
        lv2: [2, 128, 0.95]
        lv1: [1, 64, 0.95]
    use_spectral_norm: false

  sbd_params:
    h:
      pqmf_config:
        sbd: [1, 64, 0.95]
        fsbd: [1, 64, 0.95]
      sbd_filters: [[64, 128], [128, 256], [256, 512]]
      sbd_kernel_sizes: [[5, 3, 3], [5, 3, 3], [5, 3, 3]]
      sbd_dilations: [[1, 2, 4], [1, 2, 4], [1, 2, 4]]
      sbd_strides: [[2, 2, 2], [2, 2, 2], [2, 2, 2]]
      sbd_band_ranges: [[0, 32], [32, 64], [64, 128]]
      sbd_transpose: [false, true, false]
      segment_size: 1024
    use_spectral_norm: false

  mrsd_params:
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: "hann_window"
