_target_: src.model.MambaVocV2

generator_params:
  mel_configs:
    - _target_: src.utils.MelSpectrogramConfig
      sr: 22050
      win_length: 128
      hop_length: 32
      n_fft: 128
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      pad_value: -11.5129251

    - _target_: src.utils.MelSpectrogramConfig
      sr: 16000
      win_length: 16
      hop_length: 4
      n_fft: 16
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      pad_value: -11.5129251

  h:
    upsample_initial_channel: 256 # in ref repo 512
    gen_istft_n_fft: 1026

    upsample_rates: [ [ 8 ], [ 8 ]]
    upsample_kernel_sizes: [ [ 16 ], [ 18 ]]
    projection_filters: [130, 1026]
    projection_kernels: [ 5, 11 ]

discriminator_params:
  pqmf_config:
    lv1: [ 2, 256, 0.25, 10.0 ]
    lv2: [ 4, 192, 0.13, 10.0 ]
  combd_params:
    h:
      # Два discriminator-блока: первый для sub-band, второй для full-band
      combd_h_u:
        - [ 16,   64,  256, 1024, 1024, 1024 ]  # параметры первого блока
        - [ 16,   64,  256, 1024, 1024, 1024 ]  # параметы второго блока (можно те же, что и в оригинале)
      combd_d_k:
        - [ 7,  11,  11,   11,   11,   5 ]
        - [ 15,  41,  41,   41,   41,   5 ]
      combd_d_s:
        - [ 1,   1,   4,    4,    4,    1 ]
        - [ 1,   1,   4,    4,    4,    1 ]
      combd_d_d:
        - [ 1,   1,   1,    1,    1,    1 ]
        - [ 1,   1,   1,    1,    1,    1 ]
      combd_d_g:
        - [ 1,   4,   16,   64,  256,    1 ]
        - [ 1,   4,   16,   64,  256,    1 ]
      combd_d_p:
        - [ 3,   5,    5,    5,    5,    2 ]
        - [ 7,  20,   20,   20,   20,    2 ]

      # Число каналов на входе каждого projection_conv:
      # первый блок — двухканальный sub-band, второй — одноканальный full-band
      combd_op_f: [ 2, 1 ]

      # ядро и группы projection_conv — по одному на каждый блок
      combd_op_k: [ 3, 3 ]
      combd_op_g: [ 1, 1 ]
  sbd_params:
    h:
      sbd_filters: [ [ 64, 128, 256, 256, 256 ],[ 64, 128, 256, 256, 256 ],[ 64, 128, 256, 256, 256 ],[ 32, 64, 128, 128, 128 ] ]
      sbd_strides: [ [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ] ]
      sbd_kernel_sizes: [[ [ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ] ],[ [ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ] ],[ [ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ] ],[ [ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ] ]]
      sbd_dilations: [[ [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ] ],[ [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ] ],[ [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ] ],[ [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 2, 3, 5 ], [ 2, 3, 5 ] ]]
      sbd_band_ranges: [ [ 0, 6 ], [ 0, 11 ], [ 0, 16 ], [ 0, 64 ] ]
      sbd_transpose: [ False, False, False, True ]
      pqmf_config:
        sbd: [ 16, 256, 0.03, 10.0 ]
        fsbd: [ 64, 256, 0.1, 9.0 ]
      segment_size: 8192
