_target_: src.model.MambaVoc

generator_params:
  h:
    upsample_initial_channel: 256 # in ref repo 512
    gen_istft_n_fft: 1024
    gen_istft_hop_size: 256

discriminator_params:
  pqmf_config:
    lv1: [ 2, 256, 0.25, 10.0 ]
    lv2: [ 4, 192, 0.13, 10.0 ]
  combd_params:
    h:
      combd_h_u: [[ 16, 64, 256, 1024, 1024, 1024 ],[ 16, 64, 256, 1024, 1024, 1024 ],[ 16, 64, 256, 1024, 1024, 1024 ]]
      combd_d_k: [[ 7, 11, 11, 11, 11, 5 ],[ 11, 21, 21, 21, 21, 5 ],[ 15, 41, 41, 41, 41, 5 ]]
      combd_d_s: [[ 1, 1, 4, 4, 4, 1 ],[ 1, 1, 4, 4, 4, 1 ],[ 1, 1, 4, 4, 4, 1 ]]
      combd_d_d: [[ 1, 1, 1, 1, 1, 1 ],[ 1, 1, 1, 1, 1, 1 ],[ 1, 1, 1, 1, 1, 1 ]]
      combd_d_g: [[ 1, 4, 16, 64, 256, 1 ],[ 1, 4, 16, 64, 256, 1 ],[ 1, 4, 16, 64, 256, 1 ]]
      combd_d_p: [[ 3, 5, 5, 5, 5, 2 ],[ 5, 10, 10, 10, 10, 2 ],[ 7, 20, 20, 20, 20, 2 ]]

      combd_op_f: [ 1, 1, 1 ]
      combd_op_k: [ 3, 3, 3 ]
      combd_op_g: [ 1, 1, 1 ]
  sbd_params:
    h:
      use_sbd: True
      sbd_filters: [ [ 64, 128, 256, 256, 256 ],[ 64, 128, 256, 256, 256 ],[ 64, 128, 256, 256, 256 ],[ 32, 64, 128, 128, 128 ] ]
      sbd_strides: [ [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ], [ 1, 1, 3, 3, 1 ] ]
      sbd_kernel_sizes: [[ [ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ],[ 7, 7, 7 ] ],[ [ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ] ],[ [ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ],[ 3, 3, 3 ] ],[ [ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ],[ 5, 5, 5 ] ]]
      sbd_dilations: [[ [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ], [ 5, 7, 11 ] ],[ [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ], [ 3, 5, 7 ] ],[ [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ] ],[ [ 1, 2, 3 ], [ 1, 2, 3 ], [ 1, 2, 3 ], [ 2, 3, 5 ], [ 2, 3, 5 ] ]]
      sbd_band_ranges: [ [ 0, 6 ], [ 0, 11 ], [ 0, 16 ], [ 0, 64 ] ]
      sbd_transpose: [ False, False, False, True ]
      pqmf_config:
        sbd: [ 16, 256, 0.03, 10.0 ]
        fsbd: [ 64, 256, 0.1, 9.0 ]
      segment_size: 8192

mel_config:
  _target_: src.utils.MelSpectrogramConfig
  sr: 22050
  win_length: 1024
  hop_length: 256
  n_fft: 1024
  f_min: 0
  f_max: 8000
  n_mels: 80
  power: 1.0
  pad_value: -11.5129251
