_target_: src.model.MambaVocV3

generator_params:
  h:
    upsample_rates: [ 8,8,2,2 ]
    upsample_kernel_sizes: [ 16,16,4,4 ]
    upsample_initial_channel: 256

    resblock_kernel_sizes: [3,3]
    resblock_dilation_sizes: [ [ 1,3 ], [ 1,3 ], [ 1,3 ] ]

    M: 2
