defaults:
  - model: hifigan_plus_mel
  - metrics: test
  - dataloader: train
  - transforms: example_only_batch
  - _self_
datasets:
  test:
    _target_: src.datasets.LJSpeechDataset
    name: "test"
    audio_path: "datasets/vocoder_dataset"
    index_audio_path: "datasets/vocoder_dataset"
    segment_length: 466944
inferencer:
  device_tensors: ["audio", "mel"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "resynthesize_results" # any name here, can be a dataset name
  seed: 7
  from_pretrained: "/home/georgii/Documents/vocoder_3/model_best.pth" # path to the pretrained model
