_target_: src.loss.HiFiGANPaperLoss

mel_config:
    _target_: src.utils.MelSpectrogramConfig
    sr: 22050
    win_length: 1024
    hop_length: 256
    n_fft: 1024
    f_min: 0
    f_max: null
    n_mels: 80
    power: 1.0
    pad_value: -11.5129251