_target_: src.loss.LightVocLoss

# HIFIGAN like params
lambda_adv: 1.0
lambda_rec: 45.0
lambda_feature: 2.0

gen_stft_loss:
  _target_: src.loss.multi_res_stft_loss.MultiResolutionMelSpectrogramLoss
  eps: 1e-7
  device: "cuda"
  mel_configs:
    - _target_: src.utils.MelSpectrogramConfig
      sr: 22050
      win_length: 600
      hop_length: 120
      n_fft: 1024
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      pad_value: -11.5129251
    - _target_: src.utils.MelSpectrogramConfig
      sr: 16000
      win_length: 1200
      hop_length: 240
      n_fft: 2048
      f_min: 0
      f_max: 8000
      n_mels: 64
      power: 1.0
      pad_value: -11.5129251
    - _target_: src.utils.MelSpectrogramConfig
      sr: 16000
      win_length: 240
      hop_length: 50
      n_fft: 512
      f_min: 0
      f_max: 8000
      n_mels: 64
      power: 1.0
      pad_value: -11.5129251

